// packages/react/src/App.tsx
import { Icon as IconifyIcon } from "@iconify-icon/react";
import "./App.css";

function App() {
  return (
    <div className="content">
      <p>React Version</p>
      <IconifyIcon className="icon" icon="openmoji:1st-place-medal" />
      <IconifyIcon className="icon" icon="vscode-icons:file-type-access2" />
      <IconifyIcon className="icon" icon="logos:bigpanda" />
      <IconifyIcon className="icon" icon="fxemoji:2hearts" />
      <IconifyIcon className="icon" icon="flat-color-icons:businessman" />
      <IconifyIcon className="icon" icon="cif:cn" />
    </div>
  );
}

export default App;

// packages/svelte/src/App.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';
</script>

<main>
 <div class="content">
    <p>Svelte Version</p>
    <Icon class="icon" icon="openmoji:1st-place-medal" />
    <Icon class="icon" icon="vscode-icons:file-type-access2" />
    <Icon class="icon" icon="logos:bigpanda" />
    <Icon class="icon" icon="fxemoji:2hearts" />
    <Icon class="icon" icon="flat-color-icons:businessman" />
    <Icon class="icon" icon="cif:cn" />
  </div>
</main>
