// packages/preact/src/app.tsx
import { useState } from "preact/hooks";
import { Icon as IconifyIcon } from "@iconify-icon/react";
import "./app.css";

export function App() {
  return (
    <div class="content">
      <p>Preact Version</p>
      <IconifyIcon class="icon" icon="openmoji:1st-place-medal" />
      <IconifyIcon class="icon" icon="vscode-icons:file-type-access2" />
      <IconifyIcon class="icon" icon="logos:bigpanda" />
      <IconifyIcon class="icon" icon="fxemoji:2hearts" />
      <IconifyIcon class="icon" icon="flat-color-icons:businessman" />
      <IconifyIcon class="icon" icon="cif:cn" />
    </div>
  );
}

// packages/svelte/src/App.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';
</script>

<main>
 <div class="content">
    <p>Svelte Version</p>
    <Icon class="icon" icon="openmoji:1st-place-medal" />
    <Icon class="icon" icon="vscode-icons:file-type-access2" />
    <Icon class="icon" icon="logos:bigpanda" />
    <Icon class="icon" icon="fxemoji:2hearts" />
    <Icon class="icon" icon="flat-color-icons:businessman" />
    <Icon class="icon" icon="cif:cn" />
  </div>
</main>
